-- Zad 30
CREATE VIEW BANDY_INFO (NAZWA, SRE_SPOZ, MIN_SPOZ, MAX_SPOZ, KOTY, KOTY_Z_DOD) AS
SELECT nazwa, AVG(PRZYDZIAL_MYSZY), MIN(PRZYDZIAL_MYSZY), MAX(PRZYDZIAL_MYSZY), COUNT(*), COUNT(MYSZY_EXTRA)
FROM BANDY B INNER JOIN KOCURY K on B.NR_BANDY = K.NR_BANDY
HAVING count(pseudo)>0
GROUP BY nazwa;

SELECT * FROM BANDY_INFO;

SELECT 
    K.PSEUDO,
    K.IMIE,
    K.FUNKCJA,
    K.PRZYDZIAL_MYSZY,
    'OD ' || MIN_SPOZ || ' DO ' || MAX_SPOZ AS "GRANICE SPOZYCIA",
    TO_CHAR(K.W_STADKU_OD, 'YYYY-MM-DD') AS "LOWI OD"
FROM KOCURY K 
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY 
LEFT JOIN BANDY_INFO BI
    ON BI.NAZWA = B.NAZWA
WHERE K.PSEUDO = '&PSEUDONIM';

UNDEFINE PSEUDONIM

-- Zad 31
SELECT
    PSEUDO,
    PLEC,
    PRZYDZIAL_MYSZY AS "Myszy przed popdw.",
    NVL(MYSZY_EXTRA, 0) AS "Extra przed podw."
FROM KOCURY
WHERE PSEUDO IN (
    SELECT *
    FROM (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'CZARNI RYCERZE'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    ) 
    UNION
    (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'LACIACI MYSLIWI'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    )
);

UPDATE KOCURY
SET 
PRZYDZIAL_MYSZY = 
    CASE PLEC
        WHEN 'D' THEN PRZYDZIAL_MYSZY + (
            SELECT MIN(PRZYDZIAL_MYSZY) / 10.0
            FROM KOCURY
        )
        WHEN 'M' THEN PRZYDZIAL_MYSZY + 10
        ELSE PRZYDZIAL_MYSZY
    END,
MYSZY_EXTRA = NVL(MYSZY_EXTRA,0) + (
    SELECT AVG(NVL(K.MYSZY_EXTRA,0)) 
    FROM KOCURY K
    WHERE K.NR_BANDY = KOCURY.NR_BANDY
) * 0.15
WHERE PSEUDO IN (
    SELECT *
    FROM (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'CZARNI RYCERZE'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    ) 
    UNION
    (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'LACIACI MYSLIWI'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    )
);


SELECT
    PSEUDO,
    PLEC,
    PRZYDZIAL_MYSZY AS "Myszy po popdw.",
    NVL(MYSZY_EXTRA, 0) AS "Extra po podw."
FROM KOCURY
WHERE PSEUDO IN (
    SELECT *
    FROM (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'CZARNI RYCERZE'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    ) 
    UNION
    (
        SELECT *
        FROM (
            SELECT K.PSEUDO
            FROM KOCURY K 
            INNER JOIN BANDY B 
                ON K.NR_BANDY = B.NR_BANDY
            WHERE B.NAZWA = 'LACIACI MYSLIWI'
            ORDER BY K.W_STADKU_OD
        )
        WHERE ROWNUM <= 3
    )
);

ROLLBACK;

-- Zad 32a
SELECT
    NAZWA,
    DECODE(PLEC, 'M', 'Kocor', 'Kotka') AS PLEC,
    TO_CHAR(COUNT(*)) AS ILE,
    SUM(DECODE(FUNKCJA, 'SZEFUNIO', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS SZEFUNIO,
    SUM(DECODE(FUNKCJA, 'BANDZIOR', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS BANDZIOR,
    SUM(DECODE(FUNKCJA, 'LOWCZY', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS LOWCZY,
    SUM(DECODE(FUNKCJA, 'LAPACZ', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS LAPACZ,
    SUM(DECODE(FUNKCJA, 'KOT', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS KOT,
    SUM(DECODE(FUNKCJA, 'MILUSIA', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS MILUSIA,
    SUM(DECODE(FUNKCJA, 'DZIELCZY', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)) AS DZIELCZY,
    SUM(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0)) AS SUMA
FROM KOCURY INNER JOIN BANDY ON KOCURY.NR_BANDY = BANDY.NR_BANDY
GROUP BY NAZWA, PLEC
UNION
SELECT
    'ZJADA RAZEM',
    ' ',
    ' ',
    SUM(DECODE(FUNKCJA, 'SZEFUNIO', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'BANDZIOR', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'LOWCZY', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'LAPACZ', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'KOT', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'MILUSIA', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(DECODE(FUNKCJA, 'DZIELCZY', PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0),0)),
    SUM(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0))
FROM KOCURY;

-- Zad 32b
SELECT
    NAZWA,
    PLEC,
    ILE,
    NVL(SZEFUNIO,0) AS SZEFUNIO,
    NVL(BANDZIOR,0) AS BANDZIOR,
    NVL(LOWCZY,0) AS LOWCZY,
    NVL(LAPACZ,0) AS LAPACZ,
    NVL(KOT,0) AS KOT,
    NVL(MILUSIA,0) AS MILUSIA,
    NVL(DZIELCZY,0) AS DZIELCZY,
    NVL(SZEFUNIO,0) + NVL(BANDZIOR,0) + NVL(LOWCZY,0) + NVL(LAPACZ,0) + 
    NVL(KOT,0) + NVL(MILUSIA,0) + NVL(DZIELCZY,0) AS SUMA
FROM (
    SELECT
        NAZWA,
        DECODE(PLEC,'D','Kotka','Kocur') AS PLEC,
        TO_CHAR(COUNT(*) OVER (PARTITION BY NAZWA, PLEC)) as ILE,
        FUNKCJA,
        PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0) AS PRZYDZIAL
    FROM KOCURY NATURAL JOIN BANDY
)
PIVOT(
    SUM(PRZYDZIAL)
    FOR FUNKCJA IN
        ('SZEFUNIO' AS SZEFUNIO,
         'BANDZIOR' AS BANDZIOR,
         'LOWCZY' AS LOWCZY,
         'LAPACZ' AS LAPACZ,
         'KOT' AS KOT,
         'MILUSIA' AS MILUSIA,
         'DZIELCZY' AS DZIELCZY)
)
UNION
SELECT 
    'Zjada razem' AS NAZWA,
    ' ' AS PLEC,
    ' ' AS ILE,
    NVL(SZEFUNIO,0) AS SZEFUNIO,
    NVL(BANDZIOR,0) AS BANDZIOR,
    NVL(LOWCZY,0) AS LOWCZY,
    NVL(LAPACZ,0) AS LAPACZ,
    NVL(KOT,0) AS KOT,
    NVL(MILUSIA,0) AS MILUSIA,
    NVL(DZIELCZY,0) AS DZIELCZY,
    NVL(SZEFUNIO,0) + NVL(BANDZIOR,0) + NVL(LOWCZY,0) + NVL(LAPACZ,0) + 
    NVL(KOT,0) + NVL(MILUSIA,0) + NVL(DZIELCZY,0) AS SUMA
FROM (
    SELECT 
        FUNKCJA,
        PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0) AS PRZYDZIAL
    FROM KOCURY NATURAL JOIN BANDY
)
PIVOT(
    SUM(PRZYDZIAL)
    FOR FUNKCJA IN
        ('SZEFUNIO' AS SZEFUNIO,
         'BANDZIOR' AS BANDZIOR,
         'LOWCZY' AS LOWCZY,
         'LAPACZ' AS LAPACZ,
         'KOT' AS KOT,
         'MILUSIA' AS MILUSIA,
         'DZIELCZY' AS DZIELCZY)
);
