-- Zad 12
SELECT 
    K.PSEUDO AS "POLUJE W POLU",
    K.PRZYDZIAL_MYSZY AS "PRZYDZIAL MYSZY",
    B.NAZWA AS "BANDA"
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY
WHERE
    K.PRZYDZIAL_MYSZY > 50 AND 
    B.TEREN IN ('POLE', 'CALOSC');

-- Zad 13
SELECT
    K1.IMIE,
    TO_CHAR(K1.W_STADKU_OD, 'YYYY-MM-DD') AS "POLUJE OD"
FROM KOCURY K1
INNER JOIN KOCURY K2 
    ON K2.IMIE = 'JACEK'
WHERE K1.W_STADKU_OD < K2.W_STADKU_OD
ORDER BY 2 DESC;

-- Zad 14a
SELECT 
    K.IMIE,
    K.FUNKCJA,
    NVL(S1.IMIE,' ') AS "SZEF 1",
    NVL(S2.IMIE,' ') AS "SZEF 2",
    NVL(S3.IMIE,' ') AS "SZEF 3"
FROM KOCURY K
LEFT JOIN KOCURY S1 
    ON K.SZEF = S1.PSEUDO
LEFT JOIN KOCURY S2 
    ON S1.SZEF = S2.PSEUDO
LEFT JOIN KOCURY S3 
    ON S2.SZEF = S3.PSEUDO
WHERE K.FUNKCJA IN ('KOT', 'MILUSIA');

-- Zad 14b
SELECT 
    Imie,
    Funkcja,
    NVL("Szef 1", ' ') AS "SZEF 1",
    NVL("Szef 2", ' ') AS "SZEF 2",
    NVL("Szef 3", ' ') AS "SZEF 3"
FROM (
    SELECT 
        CONNECT_BY_ROOT IMIE AS Imie,
        IMIE AS S,
        CONNECT_BY_ROOT FUNKCJA AS Funkcja,
        'Szef ' || (LEVEL-1) AS HIERARCHIA
    FROM KOCURY
    WHERE LEVEL BETWEEN 2 AND 3
    START WITH FUNKCJA IN ('KOT', 'MILUSIA')
    CONNECT BY PRIOR SZEF = PSEUDO
) SRC
PIVOT(
    MAX(S)
    FOR HIERARCHIA IN ('Szef 1' AS "Szef 1", 'Szef 2' AS "Szef 2", 'Szef 3' AS "Szef 3")
);

-- Zad 14c
SELECT 
    CONNECT_BY_ROOT IMIE AS IMIE,
    CONNECT_BY_ROOT FUNKCJA AS FUNKCJA,
    LTRIM(
        SUBSTR(
            SYS_CONNECT_BY_PATH(RPAD(IMIE,15,' '), ' | '),
            LENGTH(' | ' || CONNECT_BY_ROOT(IMIE)) + 1
        )
    ) || ' |' AS "Imiona kolejnych szefów"
FROM KOCURY
WHERE CONNECT_BY_ISLEAF = 1
START WITH FUNKCJA IN ('KOT','MILUSIA')
CONNECT BY PRIOR SZEF = PSEUDO;

-- Zad 15
SELECT 
    K.IMIE,
    B.NAZWA,
    W.IMIE_WROGA, 
    W.STOPIEN_WROGOSCI AS "Ocena wroga",
    TO_CHAR(WK.DATA_INCYDENTU, 'YYYY-MM-DD') AS "Data inc."
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY
INNER JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO 
INNER JOIN WROGOWIE W 
    ON WK.IMIE_WROGA = W.IMIE_WROGA
WHERE 
    K.PLEC = 'D' AND 
    WK.DATA_INCYDENTU > TO_DATE('01.01.2007', 'DD.MM.YYYY');

-- Zad 16
SELECT
    B.NAZWA,
    COUNT(DISTINCT K.PSEUDO) AS "Koty z wrogami"
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY
INNER JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO
GROUP BY B.NAZWA;

-- Zad 17
SELECT
    K.FUNKCJA,
    K.PSEUDO,
    COUNT(*) AS "Liczba wrogow"
FROM KOCURY K
INNER JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO
GROUP BY K.FUNKCJA, K.PSEUDO
HAVING COUNT(*) > 1;

-- Zad 18
SELECT
    K.IMIE,
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 AS "DAWKA ROCZNA",
    'powyzej 864' AS DAWKA
FROM KOCURY K
WHERE 
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 > 864 
    AND K.MYSZY_EXTRA IS NOT NULL
UNION
SELECT 
    K.IMIE,
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 AS "DAWKA ROCZNA",
    '864' AS DAWKA
FROM KOCURY K
WHERE 
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 = 864 
    AND K.MYSZY_EXTRA IS NOT NULL
UNION
SELECT 
    K.IMIE,
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 AS "DAWKA ROCZNA",
    'ponizej 864' AS DAWKA
FROM KOCURY K
WHERE 
    (K.PRZYDZIAL_MYSZY + K.MYSZY_EXTRA)*12 < 864 
    AND K.MYSZY_EXTRA IS NOT NULL
ORDER BY "DAWKA ROCZNA" DESC;


-- Zad 19a
SELECT 
    B.NR_BANDY,
    B.NAZWA,
    B.TEREN
FROM BANDY B
LEFT JOIN KOCURY K 
    ON B.NR_BANDY = K.NR_BANDY
WHERE K.PSEUDO IS NULL;

-- Zad 19b
SELECT
    NR_BANDY,
    NAZWA,
    TEREN
FROM BANDY
MINUS
SELECT DISTINCT
    B.NR_BANDY,
    B.NAZWA,
    B.TEREN
FROM BANDY B
INNER JOIN KOCURY K 
    ON K.NR_BANDY = B.NR_BANDY;


-- Zad 20
SELECT
    IMIE,
    FUNKCJA,
    PRZYDZIAL_MYSZY
FROM KOCURY 
WHERE PRZYDZIAL_MYSZY >= 3 * (
    SELECT PRZYDZIAL_MYSZY
    FROM (
        SELECT KIN.PRZYDZIAL_MYSZY
        FROM KOCURY KIN
        WHERE KIN.FUNKCJA = 'MILUSIA'
        ORDER BY KIN.PRZYDZIAL_MYSZY DESC
    )
    WHERE ROWNUM = 1
);

-- Zad 21
SELECT 
    FUNKCJA,
    ROUND(AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0)),0) AS "Srednio najw. i najm. myszy"
FROM KOCURY
WHERE FUNKCJA <> 'SZEFUNIO'
GROUP BY FUNKCJA
HAVING AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0)) IN (
    (
        SELECT MIN(AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0))) 
        FROM KOCURY 
        WHERE FUNKCJA <> 'SZEFUNIO' 
        GROUP BY FUNKCJA 
    ),
    (
        SELECT MAX(AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0))) 
        FROM KOCURY 
        WHERE FUNKCJA <> 'SZEFUNIO' 
        GROUP BY FUNKCJA
    )
);

-- Zad 22a
SELECT K.PSEUDO, (K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA, 0)) AS "ZJADA"
FROM KOCURY K
WHERE &n > (
    SELECT COUNT(*)
    FROM KOCURY KIN
    WHERE (K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA,0)) < (KIN.PRZYDZIAL_MYSZY + NVL(KIN.MYSZY_EXTRA,0))
)
ORDER BY "ZJADA" DESC;

-- Zad 22b
SELECT PSEUDO, (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) "Zjada"
FROM KOCURY
WHERE (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) IN (
    SELECT * 
    FROM (
        SELECT DISTINCT (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) 
        FROM KOCURY
        ORDER BY 1 DESC
    )
    WHERE ROWNUM <= &n
);

-- Zad 22c
SELECT 
    K1.PSEUDO,
    MAX(K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA, 0)) AS "Zjada"
FROM KOCURY K1
INNER JOIN KOCURY K2 
    ON K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA,0) >= K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0)
GROUP BY K1.PSEUDO
HAVING COUNT(DISTINCT K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA, 0)) <= &n;

-- Zad 22d
SELECT PSEUDO, "Zjada"
FROM (
    SELECT 
        PSEUDO, 
        (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) "Zjada", 
        DENSE_RANK() over (ORDER BY (PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA, 0)) DESC ) POZYCJA
    From KOCURY )
Where POZYCJA <= &n;

-- Zad 23
SELECT 
    TO_CHAR(EXTRACT (YEAR FROM W_STADKU_OD)) ROK, 
    COUNT(*) AS "LICZBA WYSTAPIEN"
FROM KOCURY
GROUP BY ROK
HAVING COUNT(*) IN (
    (
        SELECT * 
        FROM (
            SELECT COUNT(*)
            FROM KOCURY
            GROUP BY EXTRACT (YEAR FROM W_STADKU_OD)
            HAVING COUNT(*) > (
                                SELECT AVG(COUNT(*))
                                FROM KOCURY
                                GROUP BY EXTRACT (YEAR FROM W_STADKU_OD))
            ORDER BY COUNT(*))
        WHERE ROWNUM = 1
    ),
    (
        SELECT * 
        FROM (
            SELECT COUNT(*)
            FROM KOCURY
            GROUP BY EXTRACT (YEAR FROM W_STADKU_OD)
            HAVING COUNT(*) < (
                                SELECT AVG(COUNT(*))
                                FROM KOCURY
                                GROUP BY EXTRACT (YEAR FROM W_STADKU_OD))
            ORDER BY COUNT(*) DESC )
        WHERE ROWNUM = 1
    )
)
UNION
SELECT 
    'Srednia' ROK, 
    ROUND(AVG(COUNT(*)),2) AS "LICZBA WYSTAPIEN"
FROM KOCURY
GROUP BY EXTRACT (YEAR FROM W_STADKU_OD);

-- Zad 24a
SELECT 
    K1.IMIE, 
    K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0) AS "Zjada", 
    K1.NR_BANDY, 
    AVG(K2.PRZYDZIAL_MYSZY + NVL(K2.MYSZY_EXTRA,0)) AS "Srednia Bandy"
FROM KOCURY K1
INNER JOIN KOCURY K2 
    ON K1.NR_BANDY = K2.NR_BANDY
WHERE K1.PLEC = 'M'
GROUP BY 
    K1.IMIE, 
    K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0), 
    K1.NR_BANDY
HAVING "Zjada" <= "Srednia Bandy";

-- Zad 24b
SELECT 
    K1.IMIE,
    K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0) AS "Zjada",
    K1.NR_BANDY,
    "Srednia Bandy"
FROM KOCURY K1
INNER JOIN (
    SELECT DISTINCT
        NR_BANDY,
        AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0)) OVER (PARTITION BY NR_BANDY) AS "Srednia Bandy"
    FROM KOCURY 
) SB ON K1.NR_BANDY = SB.NR_BANDY
WHERE K1.PLEC = 'M' 
AND K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0) <= "Srednia Bandy";

-- Zad 24c
SELECT 
    K1.IMIE,
    K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0) AS "Zjada",
    K1.NR_BANDY,
    (
        SELECT AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0))
        FROM KOCURY
        WHERE NR_BANDY = K1.NR_BANDY
        GROUP BY NR_BANDY
    ) AS "Srednia Bandy"
FROM KOCURY K1
WHERE K1.PLEC = 'M' AND
K1.PRZYDZIAL_MYSZY + NVL(K1.MYSZY_EXTRA,0) <= 
(
        SELECT AVG(PRZYDZIAL_MYSZY + NVL(MYSZY_EXTRA,0))
        FROM KOCURY
        WHERE NR_BANDY = K1.NR_BANDY
        GROUP BY NR_BANDY
);

-- Zad 25
SELECT 
    K.IMIE,
    TO_CHAR(K.W_STADKU_OD, 'YYYY-MM-DD') || ' <--- NAJMOLODSZY STAZEM W BANDZIE ' || B.NAZWA AS "WSTAPILI DO STADKA"
FROM KOCURY K
INNER JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
WHERE K.W_STADKU_OD = 
(
    SELECT MAX(W_STADKU_OD) FROM KOCURY WHERE NR_BANDY = K.NR_BANDY
)
UNION
SELECT 
    K.IMIE,
    TO_CHAR(K.W_STADKU_OD, 'YYYY-MM-DD') || ' <--- NAJSTARSZY STAZEM W BANDZIE ' || B.NAZWA AS "WSTAPILI DO STADKA"
FROM KOCURY K
INNER JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
WHERE K.W_STADKU_OD = 
(
    SELECT MIN(W_STADKU_OD) FROM KOCURY WHERE NR_BANDY = K.NR_BANDY
)
UNION
SELECT 
    K.IMIE,
    TO_CHAR(K.W_STADKU_OD, 'YYYY-MM-DD') AS "WSTAPILI DO STADKA"
FROM KOCURY K
INNER JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
WHERE K.W_STADKU_OD NOT IN (
    (
        SELECT MIN(W_STADKU_OD) FROM KOCURY WHERE NR_BANDY = K.NR_BANDY
    ),
    (
        SELECT MAX(W_STADKU_OD) FROM KOCURY WHERE NR_BANDY = K.NR_BANDY
    )
)
ORDER BY IMIE;
