-- Zad 1
SELECT K.IMIE
FROM KOCURY K
INNER JOIN KOCURY K2 
    ON K.SZEF = K2.PSEUDO
LEFT JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO
WHERE
    K.W_STADKU_OD < K2.W_STADKU_OD OR 
    WK.PSEUDO IS NULL;


-- Zad 2
SELECT
    K.PSEUDO, 
    WK.IMIE_WROGA, 
    WK.OPIS_INCYDENTU
FROM KOCURY K
INNER JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO 
WHERE K.PLEC = 'D';

-- Zad 3
SELECT 
    K.PSEUDO, 
    K.NR_BANDY
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY  
WHERE 
    K.SZEF = 'TYGRYS' AND 
    B.SZEF_BANDY <> 'TYGRYS';

-- Zad 4
SELECT
    NVL(K.PSEUDO, 'Brak przełożonego') AS PRZELOZONY,
    NVL(K2.PSEUDO, 'Brak podwładnego') AS PODWLADNY
FROM KOCURY K
FULL JOIN KOCURY K2
    ON K.PSEUDO = K2.SZEF
WHERE
    (K.PLEC = 'M' OR K.PSEUDO IS NULL) AND
    (K2.PLEC = 'M' OR K2.PSEUDO IS NULL)
ORDER BY PRZELOZONY;

-- Zad5
SELECT DISTINCT
    K.PSEUDO,
    K.PRZYDZIAL_MYSZY,
    S.SUM_W_BANDZIE,
    ROUND(K.PRZYDZIAL_MYSZY * 100.0 / S.SUM_W_BANDZIE) AS "PROC_W_BANDZIE"
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY 
INNER JOIN WROGOWIE_KOCUROW WK 
    ON K.PSEUDO = WK.PSEUDO
INNER JOIN WROGOWIE W 
    ON WK.IMIE_WROGA = W.IMIE_WROGA 
CROSS APPLY (
    SELECT SUM(PRZYDZIAL_MYSZY) AS "SUM_W_BANDZIE"
    FROM KOCURY
    WHERE NR_BANDY = K.NR_BANDY) S
WHERE
    B.TEREN IN ('POLE', 'CALOSC') AND
    W.STOPIEN_WROGOSCI > 5;

-- Zad 6
SELECT 
    K.PSEUDO,
    K.PRZYDZIAL_MYSZY,
    K.NR_BANDY,
    CASE
        WHEN K.PRZYDZIAL_MYSZY > (SELECT AVG(KI.PRZYDZIAL_MYSZY) FROM KOCURY KI ) THEN 'Prominent'
        WHEN K.PRZYDZIAL_MYSZY = (SELECT MIN(KI.PRZYDZIAL_MYSZY) FROM KOCURY KI WHERE KI.NR_BANDY = K.NR_BANDY) THEN 'Szarak'
    END AS TYP
FROM KOCURY K
WHERE
    ( K.PRZYDZIAL_MYSZY > (SELECT AVG(KI.PRZYDZIAL_MYSZY) FROM KOCURY KI) ) OR
    ( K.PRZYDZIAL_MYSZY = (SELECT MIN(KI.PRZYDZIAL_MYSZY) FROM KOCURY KI WHERE KI.NR_BANDY = K.NR_BANDY) )
ORDER BY TYP;

-- Zad 7
SELECT 
    K.PSEUDO,
    (SELECT AVG(KIN.PRZYDZIAL_MYSZY) FROM KOCURY KIN WHERE KIN.NR_BANDY = K.NR_BANDY) AS "Srednio w bandzie"
FROM KOCURY K
WHERE K.PLEC = 'M';

-- Zad 8 - A
SELECT
    K.NR_BANDY AS "Lepsze bandy",
    AVG(K.PRZYDZIAL_MYSZY) AS "Sredni przydzial w bandzie"
FROM KOCURY K
GROUP BY K.NR_BANDY
HAVING AVG(K.PRZYDZIAL_MYSZY) > (SELECT AVG(KIN.PRZYDZIAL_MYSZY) FROM KOCURY KIN);

-- Zad 8 - B
SELECT
    K.NR_BANDY AS "Lepsze bandy",
    AVG(K.PRZYDZIAL_MYSZY) AS "Sredni przydzial w bandzie",
    ROUND((SELECT AVG(KIN.PRZYDZIAL_MYSZY) FROM KOCURY KIN),2) AS "Sredni przydzial"
FROM KOCURY K
GROUP BY K.NR_BANDY
HAVING AVG(K.PRZYDZIAL_MYSZY) > (SELECT AVG(KIN.PRZYDZIAL_MYSZY) FROM KOCURY KIN);

-- Zad 9
SELECT
    TO_CHAR(K.W_STADKU_OD, 'FMMonth') AS "Miesiac",
    COUNT(*) AS "Liczba rekrutów"
FROM KOCURY K
GROUP BY 
    EXTRACT(MONTH FROM K.W_STADKU_OD),
    TO_CHAR(K.W_STADKU_OD, 'FMMonth')
ORDER BY EXTRACT(MONTH FROM K.W_STADKU_OD);

-- Zad 10
SELECT
    K.FUNKCJA,
    NVL(SUM (
        CASE WHEN B.NAZWA = 'CZARNI RYCERZE' THEN 
            K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA,0) END 
        ),0) AS "Banda CZARNI RYCERZE",
    NVL(SUM (
        CASE WHEN B.NAZWA = 'BIALI LOWCY' THEN 
            K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA,0) END 
    ),0) AS "Banda BIALI LOWCY"
FROM KOCURY K
INNER JOIN BANDY B 
    ON K.NR_BANDY = B.NR_BANDY
WHERE K.FUNKCJA <> 'SZEFUNIO'
GROUP BY K.FUNKCJA;

-- Zad 11
SELECT
	K.FUNKCJA,
	K.PLEC,
	NVL(SUM (
		CASE WHEN B.NAZWA = 'CZARNI RYCERZE' THEN
			K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA,0) END
	),0) AS "Banda CZARNI RYCERZE",
	NVL(SUM (
		CASE WHEN B.NAZWA = 'BIALI LOWCY' THEN
			K.PRZYDZIAL_MYSZY + NVL(K.MYSZY_EXTRA,0) END
	),0) AS "Banda BIALI LOWCY"
FROM KOCURY K
INNER JOIN BANDY B
	ON K.NR_BANDY = B.NR_BANDY
WHERE K.FUNKCJA <> 'SZEFUNIO'
GROUP BY K.FUNKCJA, K.PLEC;