-- Zad 30
CREATE VIEW BANDY_INFO
AS
SELECT 
    B.NAZWA AS NAZWA,
    AVG(CAST(K.PRZYDZIAL_MYSZY AS FLOAT)) AS SRE_SPOZ,
    MIN(K.PRZYDZIAL_MYSZY) AS MIN_SPOZ,
    MAX(K.PRZYDZIAL_MYSZY) AS MAX_SPOZ,
    COUNT(*) AS KOTY,
    COUNT(K.MYSZY_EXTRA) AS KOTY_Z_DOD
FROM BANDY B
INNER JOIN KOCURY K
    ON B.NR_BANDY = K.NR_BANDY
GROUP BY B.NAZWA
HAVING COUNT(K.PSEUDO) > 0;
GO

SELECT * FROM BANDY_INFO;

DECLARE @PSEUDONIM NVARCHAR(100) = 'PLACEK';
SELECT 
    K.PSEUDO,
    K.IMIE,
    K.FUNKCJA,
    K.PRZYDZIAL_MYSZY,
    'OD ' + ISNULL(CAST(BI.MIN_SPOZ AS VARCHAR(50)), '') 
        + ' DO ' + ISNULL(CAST(BI.MAX_SPOZ AS VARCHAR(50)), '') 
        AS [GRANICE SPOZYCIA],
    CONVERT(VARCHAR(10), K.W_STADKU_OD, 23) AS [LOWI OD]
FROM KOCURY K
INNER JOIN BANDY B
    ON K.NR_BANDY = B.NR_BANDY
LEFT JOIN BANDY_INFO BI
    ON BI.NAZWA = B.NAZWA
WHERE K.PSEUDO = @PSEUDONIM;

-- Zad 31
SELECT
    PSEUDO,
    PLEC,
    PRZYDZIAL_MYSZY AS "Myszy przed popdw.",
    ISNULL(MYSZY_EXTRA, 0) AS "Extra przed podw."
FROM KOCURY
WHERE PSEUDO IN (
    SELECT PSEUDO FROM (
        SELECT K.PSEUDO,
               ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'CZARNI RYCERZE'
    ) t
    WHERE rn <= 3
    UNION
    SELECT PSEUDO FROM (
        SELECT K.PSEUDO,
               ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'LACIACI MYSLIWI'
    ) t2
    WHERE rn <= 3
);

BEGIN TRAN raise;

UPDATE KOCURY
SET 
PRZYDZIAL_MYSZY = 
    CASE PLEC
        WHEN 'D' THEN PRZYDZIAL_MYSZY + (
            SELECT MIN(PRZYDZIAL_MYSZY) / 10.0
            FROM KOCURY
        )
        WHEN 'M' THEN PRZYDZIAL_MYSZY + 10
        ELSE PRZYDZIAL_MYSZY
    END,
MYSZY_EXTRA = ISNULL(MYSZY_EXTRA,0) + (
    SELECT AVG(ISNULL(K.MYSZY_EXTRA,0)) 
    FROM KOCURY K
    WHERE K.NR_BANDY = KOCURY.NR_BANDY
) * 0.15
WHERE PSEUDO IN (
    SELECT PSEUDO
    FROM (
        SELECT 
            K.PSEUDO,
            ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'CZARNI RYCERZE'
    ) t
    WHERE rn <= 3
    UNION
    SELECT PSEUDO
    FROM (
        SELECT 
            K.PSEUDO,
            ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'LACIACI MYSLIWI'
    ) t
    WHERE rn <= 3
);

SELECT
    PSEUDO,
    PLEC,
    PRZYDZIAL_MYSZY AS "Myszy po popdw.",
    ISNULL(MYSZY_EXTRA, 0) AS "Extra po podw."
FROM KOCURY
WHERE PSEUDO IN (
    SELECT PSEUDO FROM (
        SELECT K.PSEUDO,
               ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'CZARNI RYCERZE'
    ) t
    WHERE rn <= 3
    UNION
    SELECT PSEUDO FROM (
        SELECT K.PSEUDO,
               ROW_NUMBER() OVER (ORDER BY K.W_STADKU_OD) AS rn
        FROM KOCURY K 
        INNER JOIN BANDY B 
            ON K.NR_BANDY = B.NR_BANDY
        WHERE B.NAZWA = 'LACIACI MYSLIWI'
    ) t2
    WHERE rn <= 3
);

ROLLBACK;

-- Zad 32
SELECT
	B.NAZWA AS NAZWA,
	CASE WHEN K.PLEC = 'M' THEN 'Kocor' ELSE 'Kotka' END AS PLEC,
	CAST(COUNT(*) AS nvarchar(1)) AS ILE,
	SUM(CASE WHEN K.FUNKCJA = 'SZEFUNIO' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS SZEFUNIO,
	SUM(CASE WHEN K.FUNKCJA = 'BANDZIOR' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS BANDZIOR,
	SUM(CASE WHEN K.FUNKCJA = 'LOWCZY' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS LOWCZY,
	SUM(CASE WHEN K.FUNKCJA = 'LAPACZ' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS LAPACZ,
	SUM(CASE WHEN K.FUNKCJA = 'KOT' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS KOT,
	SUM(CASE WHEN K.FUNKCJA = 'MILUSIA' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS MILUSIA,
	SUM(CASE WHEN K.FUNKCJA = 'DZIELCZY' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS DZIELCZY,
	SUM(K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0)) AS SUMA
FROM KOCURY K
INNER JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
GROUP BY B.NAZWA, K.PLEC
UNION
SELECT
	'ZJADA RAZEM', ' ', ' ',
	SUM(CASE WHEN FUNKCJA = 'SZEFUNIO' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'BANDZIOR' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'LOWCZY' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'LAPACZ' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'KOT' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'MILUSIA' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(CASE WHEN FUNKCJA = 'DZIELCZY' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
	SUM(PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0))
FROM KOCURY;

SELECT
    CASE WHEN K.PLEC = 'M' THEN ' ' ELSE B.NAZWA END AS NAZWA,
    CASE WHEN K.PLEC = 'M' THEN 'Kocor' ELSE 'Kotka' END AS PLEC,
    COUNT(*) AS ILE,
    SUM(CASE WHEN K.FUNKCJA = 'SZEFUNIO' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS SZEFUNIO,
    SUM(CASE WHEN K.FUNKCJA = 'BANDZIOR' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS BANDZIOR,
    SUM(CASE WHEN K.FUNKCJA = 'LOWCZY' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS LOWCZY,
    SUM(CASE WHEN K.FUNKCJA = 'LAPACZ' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS LAPACZ,
    SUM(CASE WHEN K.FUNKCJA = 'KOT' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS KOT,
    SUM(CASE WHEN K.FUNKCJA = 'MILUSIA' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS MILUSIA,
    SUM(CASE WHEN K.FUNKCJA = 'DZIELCZY' THEN K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0) ELSE 0 END) AS DZIELCZY,
    SUM(K.PRZYDZIAL_MYSZY + ISNULL(K.MYSZY_EXTRA,0)) AS SUMA
FROM KOCURY K
INNER JOIN BANDY B ON K.NR_BANDY = B.NR_BANDY
GROUP BY B.NAZWA, K.PLEC

UNION
SELECT
    'ZJADA RAZEM', ' ', NULL,
    SUM(CASE WHEN FUNKCJA = 'SZEFUNIO' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'BANDZIOR' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'LOWCZY' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'LAPACZ' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'KOT' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'MILUSIA' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(CASE WHEN FUNKCJA = 'DZIELCZY' THEN PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) ELSE 0 END),
    SUM(PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0))
FROM KOCURY;


-- 32b
SELECT
    NAZWA,
    PLEC,
    CAST(ILE AS nvarchar(1)),
    ISNULL(SZEFUNIO,0) AS SZEFUNIO,
    ISNULL(BANDZIOR,0) AS BANDZIOR,
    ISNULL(LOWCZY,0) AS LOWCZY,
    ISNULL(LAPACZ,0) AS LAPACZ,
    ISNULL(KOT,0) AS KOT,
    ISNULL(MILUSIA,0) AS MILUSIA,
    ISNULL(DZIELCZY,0) AS DZIELCZY,
    ISNULL(SZEFUNIO,0) + ISNULL(BANDZIOR,0) + ISNULL(LOWCZY,0) + ISNULL(LAPACZ,0) + 
    ISNULL(KOT,0) + ISNULL(MILUSIA,0) + ISNULL(DZIELCZY,0) AS SUMA
FROM (
    SELECT
        NAZWA,
        CASE WHEN PLEC = 'D' THEN 'Kotka' ELSE 'Kocur' END AS PLEC,
        COUNT(*) OVER (PARTITION BY NAZWA, PLEC) AS ILE,
        FUNKCJA,
        PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) AS PRZYDZIAL
    FROM KOCURY
    INNER JOIN BANDY ON KOCURY.NR_BANDY = BANDY.NR_BANDY
) AS src
PIVOT (
    SUM(PRZYDZIAL)
    FOR FUNKCJA IN (
        "SZEFUNIO", "BANDZIOR", "LOWCZY", "LAPACZ", "KOT", "MILUSIA", "DZIELCZY"
    )
) AS pvt

UNION ALL

SELECT
    'Zjada razem' AS NAZWA,
    ' ' AS PLEC,
    ' ' AS ILE,
    ISNULL(SZEFUNIO,0) AS SZEFUNIO,
    ISNULL(BANDZIOR,0) AS BANDZIOR,
    ISNULL(LOWCZY,0) AS LOWCZY,
    ISNULL(LAPACZ,0) AS LAPACZ,
    ISNULL(KOT,0) AS KOT,
    ISNULL(MILUSIA,0) AS MILUSIA,
    ISNULL(DZIELCZY,0) AS DZIELCZY,
    ISNULL(SZEFUNIO,0) + ISNULL(BANDZIOR,0) + ISNULL(LOWCZY,0) + ISNULL(LAPACZ,0) + 
    ISNULL(KOT,0) + ISNULL(MILUSIA,0) + ISNULL(DZIELCZY,0) AS SUMA
FROM (
    SELECT
        FUNKCJA,
        PRZYDZIAL_MYSZY + ISNULL(MYSZY_EXTRA,0) AS PRZYDZIAL
    FROM KOCURY
    INNER JOIN BANDY ON KOCURY.NR_BANDY = BANDY.NR_BANDY
) AS src
PIVOT (
    SUM(PRZYDZIAL)
    FOR FUNKCJA IN (
        "SZEFUNIO", "BANDZIOR", "LOWCZY", "LAPACZ", "KOT", "MILUSIA", "DZIELCZY"
    )
) AS pvt;